name: diet_driven
author: Dennis Krasnov <dennis.krasnov@gmail.com>
description: No compromises calorie counter.

version: 1.0.2+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## BLOC
  bloc: ^0.9.5
  flutter_bloc: ^0.7.1
  equatable: ^0.2.0

  ## FIREBASE
  cloud_firestore: ^0.9.6
  cloud_functions: ^0.1.1+1
  firebase_auth: ^0.8.1+4
  firebase_remote_config: ^0.1.0+2
  firebase_analytics: ^2.0.2+1
  google_sign_in: ^4.0.1+1

  ## UTILS
  dio: ^2.1.0
  flare_flutter: ^1.3.4
  connectivity: ^0.4.2
  logging: ^0.11.3+2
  intl: ^0.15.7
  date_utils: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  ## BUILT VALUE
  build: ^1.0.2
  build_runner: ^1.1.2
  built_value: ^6.2.0
  built_collection: ^4.1.0
  built_value_generator: ^6.2.0

  ## TESTING
  test: ^1.5.3
  mockito: ^4.0.0

  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SourceSansPro
      fonts:
      - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
      - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
    - family: FiraSans
      fonts:
      - asset: fonts/Fira_Sans/FiraSans-Regular.ttf
