name: diet_driven
author: Dennis Krasnov <dennis.krasnov@gmail.com>
description: No compromises calorie counter.

version: 1.0.2+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## BLOC
  rxdart: ^0.22.0
  bloc: ^0.14.2
  flutter_bloc: ^0.16.0

  ## FIREBASE
#  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.12.5
  cloud_functions: ^0.4.0
  firebase_auth: ^0.11.1+6
  firebase_remote_config: ^0.2.0+2
  firebase_analytics: ^3.0.2
  google_sign_in: ^4.0.1+3

  ## UTILS
  dio: ^2.1.3
  flare_flutter: ^1.3.6
  connectivity: ^0.4.2+1
  logging: ^0.11.3+2
  intl: ^0.15.8
  date_utils: ^0.1.0+2
  uuid: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_driver: - Incompatible with intl
  #  sdk: flutter

  ## TESTING
#  test: ^1.6.1 - Incompatible with flutter test
  test: ^1.5.3
  mockito: ^4.0.0

  ## BUILT VALUE
  build: ^1.1.4
  build_runner: ^1.5.0
  built_value: ^6.6.0
  built_collection: ^4.2.2
  built_value_generator: ^6.6.0

#  pedantic: ^1.7.0
  flutter_launcher_icons: ^0.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SourceSansPro
      fonts:
      - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
      - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
    - family: FiraSans
      fonts:
      - asset: fonts/Fira_Sans/FiraSans-Regular.ttf
