name: bloc_logging
description: Logging utility library for using 'bloc' package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ansicolor: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
