name: diet_driven
description: No compromises calorie counter.
version: 1.1.0+6
author: Dennis Krasnov <dennis@krasnov.dev>
homepage: https://github.com/Dennis-Krasnov/Diet-Driven

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## BLOC
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  rxdart: ^0.22.6

  ## FIREBASE
  cloud_firestore: ^0.12.9+4
  cloud_functions: ^0.4.1+1
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_remote_config: ^0.2.0+7
  # google_sign_in: ^4.0.1+3

  ## CONFIGURATION
  connectivity: ^0.4.4
  package_info: ^0.4.0+6
  # device_info

  ## FLUTTER WIDGETS
  syncfusion_flutter_charts: ^17.3.26
  font_awesome_flutter: ^8.5.0
  flare_flutter: 1.5.12
  shimmer: ^1.0.1
  flutter_material_color_picker: ^1.0.5
  flutter_sticky_header: ^0.4.0
#  sticky_headers: ^0.1.8
  deep_link_navigation: ^1.2.1

  ## DART UTILS

  time: ^1.1.1
#  date_utils: ^0.1.0+2
  dio: ^3.0.3
#  intl: ^0.15.8 # ^0.16.0
#  intl: ^0.15.8 # ^0.16.0
  merge_map: ^1.0.2
  uuid: ^2.0.2
  bloc_logging:
    path: ../bloc_logging

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  ## TESTING
  test: ^1.5.3
  bloc_test: ^2.2.2
#  test: ^1.8.0 TODO
  mockito: ^4.0.0

  ## BUILT VALUE
  build: ^1.2.2
  build_runner: ^1.7.2
  built_collection: ^4.3.0
  built_value: ^7.0.0
  built_value_generator: ^7.0.0

#  pedantic: ^1.7.0
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    # https://github.com/rsms/inter
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-Bold.otf
          weight: 700
