name: diet_driven
author: Dennis Krasnov <dennis@krasnov.dev>
description: No compromises calorie counter.

version: 1.1.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## BLOC
  bloc: ^0.14.4
  flutter_bloc: ^0.20.0
  rxdart: ^0.22.1

  ## FIREBASE
  cloud_firestore: ^0.12.9
  cloud_functions: ^0.4.1
  firebase_analytics: ^3.0.3 # TODO: ^5.0.0
  firebase_auth: ^0.14.0
  firebase_remote_config: ^0.2.0+5
  # google_sign_in: ^4.0.1+3

  ## CONFIGURATION
  connectivity: ^0.4.3+6
  package_info: ^0.4.0+6
  # device_info

  ## FLUTTER WIDGETS
  charts_flutter: ^0.7.0
  font_awesome_flutter: ^8.5.0
  flare_flutter: ^1.5.5
  shimmer: ^1.0.0
  flutter_material_color_picker: ^1.0.3
  sticky_headers: "^0.1.8"

  ## DART UTILS
  ansicolor: ^1.0.2
  date_utils: ^0.1.0+2
  dio: ^2.1.13
  intl: ^0.15.8
  merge_map: ^1.0.2
  uuid: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_driver: - Incompatible with intl
  #  sdk: flutter

  ## TESTING
#  test: ^1.6.1 - Incompatible with flutter test
  test: ^1.5.3
  mockito: ^4.0.0

  ## BUILT VALUE
  build: ^1.1.5
  build_runner: ^1.6.5
  built_collection: ^4.2.2
  built_value: ^6.7.0
  built_value_generator: ^6.7.0

#  pedantic: ^1.7.0
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    # https://github.com/rsms/inter
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-Bold.otf
          weight: 700
